#!/usr/bin/env bash
# Configure + install Bureau as persistent systemd services inside WSL. Idempotent.
# Encodes every fix the runbook audit surfaced:
#   - explicit Linux-first PATH baked into the unit (the shell-free spawn crux), incl. ~/.local/bin
#     for the claude CLI, and OMITTING /mnt/c so npm/corepack can't resolve to Windows shims.
#   - `corepack enable` so a bare `pnpm` (what provision spawns) resolves.
#   - ANTHROPIC_API_KEY left UNSET so the already-authed claude CLI is the provider.
#   - absolute data paths (repos root, DB, AND vault) on the native FS, outside the git checkout.
#   - a systemd SYSTEM service (Restart=always) that survives session close + restarts on crash.
set -euo pipefail

log() { echo "==> $*"; }

# --- resolve the Linux toolchain (this shell may be non-login) ---
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
nvm use 24 >/dev/null 2>&1 || true            # pin: install-node == engine-node (better-sqlite3 ABI)
NODE_BIN="$(command -v node)"
NODE_DIR="$(dirname "$NODE_BIN")"
export PATH="$NODE_DIR:$HOME/.bun/bin:$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"

# The PATH the engine process (and its shell-free child spawns) must have. Linux dirs FIRST,
# claude included, /mnt/c excluded so bun/pnpm/npm/node/git/gh/claude all resolve Linux-side.
ENGINE_PATH="$NODE_DIR:$HOME/.bun/bin:$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin"

REPO="$HOME/bureau"
DATA="$HOME/.bureau-data"        # runtime data OUTSIDE the git checkout (survives a redeploy reset)
GH_BIN="$(command -v gh || echo /usr/bin/gh)"
GIT_BIN="$(command -v git || echo /usr/bin/git)"
BUN_V="$(bun --version 2>/dev/null || echo '?')"
# Commit identity for Bureau's PRs — reuse the machine's git config, fall back to a placeholder.
AUTHOR_NAME="${BUREAU_AUTHOR_NAME:-$(git config --global user.name 2>/dev/null || echo Bureau)}"
AUTHOR_EMAIL="${BUREAU_AUTHOR_EMAIL:-$(git config --global user.email 2>/dev/null || echo bureau@localhost)}"

log "node $($NODE_BIN --version) @ $NODE_DIR | bun $BUN_V | claude $(command -v claude) | gh $GH_BIN"

# --- corepack: materialize a bare `pnpm` shim (provision.ts spawns bare "pnpm") ---
log "corepack enable (provides a bare pnpm on PATH)"
corepack enable 2>/dev/null || corepack enable --install-directory "$NODE_DIR" 2>/dev/null || true
command -v pnpm >/dev/null 2>&1 && log "pnpm shim: $(command -v pnpm) ($(pnpm --version 2>&1 | head -1))" || log "WARN: pnpm shim not found"

# --- data dirs (native FS, absolute) ---
mkdir -p "$DATA/repos"
log "data root: $DATA (repos/, bureau.db, vault/)"

# --- engine .env (BUREAU_* only; PATH comes from the unit; NO ANTHROPIC_API_KEY → claude CLI) ---
log "writing $REPO/apps/engine/.env"
cat > "$REPO/apps/engine/.env" <<ENV
# Generated by deploy/wsl/02-setup.sh — Bureau-in-WSL.
BUREAU_REPOS_ROOT=$DATA/repos
BUREAU_DB=$DATA/bureau.db
BUREAU_VAULT=$DATA/vault
BUREAU_GH_PATH=$GH_BIN
BUREAU_GIT_PATH=$GIT_BIN
BUREAU_AUTHOR_NAME=$AUTHOR_NAME
BUREAU_AUTHOR_EMAIL=$AUTHOR_EMAIL
PORT=4319
# ANTHROPIC_API_KEY intentionally omitted — the engine then uses the authenticated claude CLI.
ENV

# --- build the panel for production (NEXT_PUBLIC_* is inlined at build time) ---
log "building the panel (next build)"
( cd "$REPO" && NEXT_PUBLIC_ENGINE_URL=http://localhost:4319 corepack pnpm --filter @bureau/panel build ) 2>&1 | tail -6

# --- systemd units (SYSTEM services; survive session close, restart on crash) ---
log "installing systemd units"
sudo tee /etc/systemd/system/bureau-engine.service >/dev/null <<UNIT
[Unit]
Description=Bureau engine (HTTP + WebSocket daemon, localhost only)
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$REPO/apps/engine
Environment=HOME=$HOME
Environment=PATH=$ENGINE_PATH
ExecStart=$NODE_BIN $REPO/apps/engine/dist/server.js
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
UNIT

sudo tee /etc/systemd/system/bureau-panel.service >/dev/null <<UNIT
[Unit]
Description=Bureau panel (Next.js, localhost:3000)
After=network.target bureau-engine.service

[Service]
Type=simple
User=$USER
WorkingDirectory=$REPO
Environment=HOME=$HOME
Environment=PATH=$ENGINE_PATH
Environment=NEXT_PUBLIC_ENGINE_URL=http://localhost:4319
ExecStart=$NODE_DIR/corepack pnpm --filter @bureau/panel start
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
UNIT

sudo systemctl daemon-reload
sudo systemctl enable --now bureau-engine.service
sudo systemctl enable --now bureau-panel.service

# --- wait + health-check ---
log "waiting for the engine to answer on 127.0.0.1:4319"
ok=""
for i in $(seq 1 30); do
  if curl -fsS -o /dev/null http://127.0.0.1:4319/api/config 2>/dev/null; then ok=1; break; fi
  sleep 1
done
echo "----- bureau-engine status -----"
systemctl --no-pager --full status bureau-engine.service | sed -n '1,8p' || true
echo "----- /api/config (engine self-report) -----"
curl -fsS http://127.0.0.1:4319/api/config 2>&1 | head -c 600; echo
echo "----- panel -----"
for i in $(seq 1 30); do curl -fsS -o /dev/null http://127.0.0.1:3000 2>/dev/null && { echo "panel OK on :3000"; break; }; sleep 1; done
[ -n "$ok" ] && log "ENGINE UP" || { log "ENGINE DID NOT ANSWER — recent logs:"; journalctl -u bureau-engine --no-pager -n 30 || true; exit 1; }
log "DONE."
